name: Build and Publish
on: [push]

jobs:
    build:
      runs-on: windows-latest
      strategy:
          matrix:
            configuration: ['Release', 'Debug']
      steps:
      - uses: actions/checkout@master
      - name: Get Depedencies
        run: dotnet restore
        working-directory: ./src
      - name: Build
        run: dotnet build --configuration ${{ matrix.configuration }} --no-restore
        working-directory: ./src
      - name: Archive build results
        uses: actions/upload-artifact@v2
        with:
          name: windows_build_${{ matrix.configuration }}
          path: src/KanimExplorer/bin/${{ matrix.configuration }}
      #- name: Create Release
      #  id: create_release
      #  uses: actions/create-release@v1
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      #  with:
      #    tag_name: ${{ github.ref }}
      #    release_name: Release ${{ github.ref }}
      #    body: |
      #      Changes in this Release
      #      - First Change
      #      - Second Change
      #    draft: false
      #    prerelease: false
      #- name: Create Release archive
      #  shell: pwsh
      #  run: Compress-Archive src/KanimExplorer/bin/${{ matrix.configuration }} Windows.${{ matrix.configuration }}.zip
      #- name: Upload Release Asset
      #  id: upload-release-asset 
      #  uses: actions/upload-release-asset@v1
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  with:
      #    upload_url: ${{ steps.create_release.outputs.upload_url }}
      #    asset_path: ./Windows.${{ matrix.configuration }}.zip
      #    asset_name: Windows.${{ matrix.configuration }}.zip
      #    asset_content_type: application/zip
